# Generated by Django 4.0.5 on 2022-07-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_curta', models.CharField(max_length=200)),
                ('descricao_longa', models.TextField()),
            ],
        ),
    ]
