# Generated by Django 4.0.5 on 2022-06-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobre_nome', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d')),
            ],
        ),
    ]
