# Generated by Django 4.0.5 on 2022-06-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
    ]
