# Generated by Django 4.0.5 on 2022-06-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_contato_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='sobre_nome',
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
