# Generated by Django 4.0.5 on 2022-07-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_rename_contato_pessoacontato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PessoaContato',
        ),
    ]
